import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Next App with Tailwind CSS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-auto min-h-screen">
        <h1>Next.js with Tailwind</h1>
      </main>
    </>
  );
}
